#!/bin/bash
shopt -s globstar

LINTER_HOME=$(dirname $0)
FILE_PATH=/mnt/d/hexlet_folder/algo_inheritance/html-tasks/**/

CSS_FILE_GLOB=$FILE_PATH*.css
SCSS_FILE_GLOB=$FILE_PATH*.scss
HTML_FILE_GLOB=$FILE_PATH*.html
EXIT_CODE=0

set_exit_code() {
  if [ ! $? == "0" ]; then EXIT_CODE=1; fi
}
if compgen -G $CSS_FILE_GLOB > /dev/null; then
  $LINTER_HOME/node_modules/.bin/stylelint $CSS_FILE_GLOB --config $LINTER_HOME/.stylelintrc
  set_exit_code
fi

if compgen -G $SCSS_FILE_GLOB > /dev/null; then
  $LINTER_HOME/node_modules/.bin/stylelint $SCSS_FILE_GLOB --config $LINTER_HOME/.stylelintrc
  set_exit_code
fi

exit $EXIT_CODE